//! Exact Pythagorean-hodograph path carriers and inverse-length replay.
//!
//! Pythagorean-hodograph (PH) curves are the path-domain tool Farouki and
//! Sakkalis introduced for polynomial curves whose speed is polynomial instead
//! of a square root. This module starts with the cubic PH case generated by a
//! linear complex hodograph `w(t) = u(t) + i v(t)`, where
//! `x'(t) = u(t)^2 - v(t)^2`, `y'(t) = 2 u(t) v(t)`, and speed is exactly
//! `u(t)^2 + v(t)^2`. See Farouki and Sakkalis, "Pythagorean hodographs",
//! *IBM Journal of Research and Development* 34.5 (1990).
//!
//! The implementation follows Yap, "Towards Exact Geometric Computation,"
//! *Computational Geometry* 7.1-2 (1997): the curve and inverse-length
//! parameter are retained as exact algebraic candidates, then `hypersolve`
//! replays the denominator-free polynomial residual before accepting them.

use hyperlimit::Point2;
use hyperreal::{Real, RealExactSetFacts, RealSign};
use hypersolve::{
    CandidateCertificationReport, Constraint, Expr, PreparedProblem, Problem, certify_candidate,
    context_from_problem,
};

use crate::bezier::BezierParameter;
use crate::provenance::PathProvenance;

/// Cached exact facts for a cubic PH span.
#[derive(Clone, Debug, PartialEq)]
pub struct CubicPhFacts {
    /// Exact-set facts across start point and hodograph coordinates.
    pub exact: RealExactSetFacts,
    /// Exact endpoint obtained by integrating the retained hodograph.
    pub end: Point2,
    /// Exact polynomial arc length over `[0, 1]`.
    pub exact_length: Real,
    /// Source provenance for this retained path object.
    pub provenance: PathProvenance,
}

/// Retained cubic Pythagorean-hodograph curve.
///
/// The stored scalars are endpoint values of the linear complex hodograph
/// `u(t), v(t)`. Integrating the squared complex hodograph gives the endpoint,
/// while integrating `u^2 + v^2` gives an exact polynomial length. That makes
/// this carrier a native PH object for feed replay and inverse-length
/// certification, not a sampled Bezier approximation.
#[derive(Clone, Debug, PartialEq)]
pub struct CubicPythagoreanHodograph {
    start: Point2,
    u0: Real,
    v0: Real,
    u1: Real,
    v1: Real,
    facts: CubicPhFacts,
}

/// Exact inverse-length replay report for a cubic PH span.
#[derive(Clone, Debug)]
pub struct CubicPhInverseLengthReport {
    /// Exact curve being inverted.
    pub curve: CubicPythagoreanHodograph,
    /// Exact target length from the start of the curve.
    pub target_length: Real,
    /// Exact candidate parameter in `[0, 1]`.
    pub parameter: BezierParameter,
    /// Solver replay report for the cubic inverse-length residual.
    pub certification: CandidateCertificationReport,
}

/// Errors while constructing or replaying exact PH carriers.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum PhCurveError {
    /// The retained hodograph is structurally zero-length over the full span.
    DegenerateHodograph,
    /// Exact scalar division failed while integrating the hodograph.
    UnsupportedDivision,
    /// Target length was structurally negative.
    NegativeLength,
}

impl CubicPythagoreanHodograph {
    /// Construct a cubic PH span with native provenance.
    pub fn new(
        start: Point2,
        u0: Real,
        v0: Real,
        u1: Real,
        v1: Real,
    ) -> Result<Self, PhCurveError> {
        Self::with_provenance(start, u0, v0, u1, v1, PathProvenance::native())
    }

    /// Construct a cubic PH span with retained source provenance.
    ///
    /// The endpoint and exact length are integrated immediately as retained
    /// facts. For a linear hodograph, the exact total length is
    /// `(u0^2 + u0*u1 + u1^2 + v0^2 + v0*v1 + v1^2) / 3`; endpoint
    /// displacement uses the corresponding integrals of `u^2 - v^2` and
    /// `2uv`. These are the polynomial PH length identities described by
    /// Farouki and Sakkalis (1990), kept exact for Yap-style certification.
    pub fn with_provenance(
        start: Point2,
        u0: Real,
        v0: Real,
        u1: Real,
        v1: Real,
        provenance: PathProvenance,
    ) -> Result<Self, PhCurveError> {
        let facts = cubic_ph_facts(&start, &u0, &v0, &u1, &v1, provenance)?;
        if facts.exact_length.structural_facts().sign == Some(RealSign::Zero) {
            return Err(PhCurveError::DegenerateHodograph);
        }
        Ok(Self {
            start,
            u0,
            v0,
            u1,
            v1,
            facts,
        })
    }

    /// Return the exact start point.
    pub const fn start(&self) -> &Point2 {
        &self.start
    }

    /// Return the exact endpoint obtained by PH integration.
    pub const fn end(&self) -> &Point2 {
        &self.facts.end
    }

    /// Return cached exact PH facts.
    pub const fn facts(&self) -> &CubicPhFacts {
        &self.facts
    }

    /// Return path source provenance.
    pub const fn provenance(&self) -> PathProvenance {
        self.facts.provenance
    }

    /// Return exact total PH arc length over `[0, 1]`.
    pub fn exact_length(&self) -> Real {
        self.facts.exact_length.clone()
    }

    /// Return exact PH arc length from `0` to `parameter`.
    ///
    /// For `u(t)=u0+(u1-u0)t` and `v(t)=v0+(v1-v0)t`, speed is the quadratic
    /// polynomial `A + B*t + C*t^2`; the partial length is
    /// `A*t + B*t^2/2 + C*t^3/3`. No square root or numeric quadrature is
    /// involved.
    pub fn partial_length(&self, parameter: BezierParameter) -> Result<Real, PhCurveError> {
        let (a, b, c) = self.speed_polynomial_coefficients();
        let t = parameter.to_real();
        let t2 = t.clone() * t.clone();
        let t3 = t2.clone() * t.clone();
        let half = (b * t2 / Real::from(2)).map_err(|_| PhCurveError::UnsupportedDivision)?;
        let third = (c * t3 / Real::from(3)).map_err(|_| PhCurveError::UnsupportedDivision)?;
        Ok(a * t + half + third)
    }

    /// Return the exact quadratic speed polynomial coefficients `(A, B, C)`.
    pub fn speed_polynomial_coefficients(&self) -> (Real, Real, Real) {
        let du = self.u1.clone() - self.u0.clone();
        let dv = self.v1.clone() - self.v0.clone();
        let a = self.u0.clone() * self.u0.clone() + self.v0.clone() * self.v0.clone();
        let b = Real::from(2) * (self.u0.clone() * du.clone() + self.v0.clone() * dv.clone());
        let c = du.clone() * du + dv.clone() * dv;
        (a, b, c)
    }
}

/// Certify a candidate inverse-length parameter for a cubic PH span.
///
/// The residual is the denominator-free polynomial
/// `6*s - 6*A*t - 3*B*t^2 - 2*C*t^3 = 0`, where `s` is target length and
/// `(A, B, C)` are the exact speed polynomial coefficients. This is a native
/// PH inverse-length replay: a caller may propose `t`, but exact arithmetic
/// decides whether that proposal matches the retained length.
pub fn certify_cubic_ph_inverse_length(
    curve: &CubicPythagoreanHodograph,
    target_length: Real,
    parameter: BezierParameter,
) -> Result<CubicPhInverseLengthReport, PhCurveError> {
    if target_length.structural_facts().sign == Some(RealSign::Negative) {
        return Err(PhCurveError::NegativeLength);
    }
    let (a, b, c) = curve.speed_polynomial_coefficients();
    let mut problem = Problem::default();
    let t = problem.add_variable("parameter", parameter.to_real());
    let t_expr = Expr::symbol(t.into(), "parameter");
    problem.add_constraint(Constraint::equality(
        "cubic PH inverse length",
        Expr::real(Real::from(6) * target_length.clone())
            - Expr::real(Real::from(6) * a) * t_expr.clone()
            - Expr::real(Real::from(3) * b) * t_expr.clone() * t_expr.clone()
            - Expr::real(Real::from(2) * c) * t_expr.clone() * t_expr.clone() * t_expr,
    ));
    let prepared = PreparedProblem::new(&problem);
    let context = context_from_problem(&problem);
    Ok(CubicPhInverseLengthReport {
        curve: curve.clone(),
        target_length,
        parameter,
        certification: certify_candidate(&prepared, &context),
    })
}

fn cubic_ph_facts(
    start: &Point2,
    u0: &Real,
    v0: &Real,
    u1: &Real,
    v1: &Real,
    provenance: PathProvenance,
) -> Result<CubicPhFacts, PhCurveError> {
    let u_integral = quadratic_endpoint_integral(u0, u1);
    let v_integral = quadratic_endpoint_integral(v0, v1);
    let exact_length = ((u_integral.clone() + v_integral.clone()) / Real::from(3))
        .map_err(|_| PhCurveError::UnsupportedDivision)?;
    let dx = ((u_integral - v_integral) / Real::from(3))
        .map_err(|_| PhCurveError::UnsupportedDivision)?;
    let uv = Real::from(2) * u0.clone() * v0.clone()
        + u0.clone() * v1.clone()
        + u1.clone() * v0.clone()
        + Real::from(2) * u1.clone() * v1.clone();
    let dy = (uv / Real::from(3)).map_err(|_| PhCurveError::UnsupportedDivision)?;
    let end = Point2::new(start.x.clone() + dx, start.y.clone() + dy);
    Ok(CubicPhFacts {
        exact: Real::exact_set_facts([
            &start.x,
            &start.y,
            u0,
            v0,
            u1,
            v1,
            &end.x,
            &end.y,
            &exact_length,
        ]),
        end,
        exact_length,
        provenance,
    })
}

fn quadratic_endpoint_integral(start: &Real, end: &Real) -> Real {
    start.clone() * start.clone() + start.clone() * end.clone() + end.clone() * end.clone()
}
